<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml [
    <!ELEMENT xml (records)>
    <!ELEMENT records (record+)>
    <!ELEMENT record (contributors, auth-address?, titles, periodical?, pages?, volume?, number?, edition?, keywords, year, isbn?, pub-location?, publisher?, abstract?, work-type, urls, electronic-resource-num?, remote-database-provider, language)>
    <!ELEMENT contributors (authors, secondary-authors?)>
    <!ELEMENT auth-address (#PCDATA)>
    <!ELEMENT authors (author+)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT secondary-authors (author+)>
    <!ELEMENT titles (title, secondary-title?, translated-title?)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT secondary-title (#PCDATA)>  
    <!ELEMENT translated-title (#PCDATA)>  
    <!ELEMENT periodical (full-title)>
    <!ELEMENT full-title (#PCDATA)>
    <!ELEMENT pages (#PCDATA)>
    <!ELEMENT number (#PCDATA)>
    <!ELEMENT volume (#PCDATA)>
    <!ELEMENT edition (#PCDATA)>
    <!ELEMENT keywords (keyword+)>
    <!ELEMENT keyword (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT isbn (#PCDATA)>
    <!ELEMENT pub-location (#PCDATA)>
    <!ELEMENT publisher (#PCDATA)>
    <!ELEMENT abstract (#PCDATA)>
    <!ELEMENT work-type (#PCDATA)>
    <!ELEMENT urls (related-urls*, pdf-urls?)>
    <!ELEMENT related-urls (url+)>
    <!ELEMENT url (#PCDATA)>
    <!ELEMENT pdf-urls (url)>
    <!ELEMENT electronic-resource-num (#PCDATA)>
    <!ELEMENT remote-database-provider (#PCDATA)>
    <!ELEMENT language (#PCDATA)>
]>
<xml>
    <records>
        <record>
            <contributors>
                <authors>
                    <author>
                        Black, R. E.
                    </author>
                    <author>
                        Walker, N.
                    </author>
                    <author>
                        Laxminarayan, R.
                    </author>
                    <author>
                        Temmerman, M.
                    </author>
                </authors>
            </contributors>
            <titles>
                <title>
                    Reproductive, Maternal, Newborn,
                    and Child Health
                </title>
            </titles>
            <volume>
                2
            </volume>
            <edition>
                3rd
            </edition>
            <keywords>
                <keyword>
                    disease detection
                </keyword>
            </keywords>
            <year>
                2016
            </year>
            <pub-location>
                Washington (DC)
            </pub-location>
            <publisher>
                The International Bank for Reconstruction and Development
            </publisher>
            <abstract>
                Reproductive, maternal, newborn, and child health (RMNCH) has been a priority
                for both governments and civil society in low- and middle-income countries (LMICs).
                This priority was affirmed by world leaders in the Millennium Development Goals
                (MDGs)
                that called for countries to reduce child mortality by 67 percent and maternal
                mortality by 75 percent between 1990 and 2015. Although substantial progress on
                these targets has been made, few countries achieved the needed reductions. The
                United Nations (UN) Secretary-General’s Global Strategy for Women’s and Children’s
                Health, launched in 2010 and expanded in 2015 to include adolescents, is an
                indication
                of the continued global commitment to the survival and well-being of women and
                children
                (Ban 2010). Annual official development assistance for maternal, newborn, and
                child health has increased from US$2.7 billion in 2003 to US$8.3 billion in
                2012, when there was an additional US$4.5 billion for reproductive health
                (Arregoces and others 2015). A continued focus on RMNCH is needed to address the
                remaining considerable burden of disease in LMICs from unwanted pregnancies;
                high maternal, newborn, and child mortality and stillbirths; high rates of
                undernutrition; frequent communicable and noncommunicable diseases; and loss of
                human capacity. Cost-effective interventions are available and can be
                implemented at high coverage in LMICs to greatly reduce these problems at an
                affordable cost. RMNCH encompasses health problems across the life course from
                adolescent girls and women before and during pregnancy and delivery, to newborns
                and children. An important conceptual framework is the continuum-of-care
                approach in two dimensions. One dimension recognizes the links from mother to
                child and the need for health services across the stages of the life course. The
                other is the delivery of integrated preventive and therapeutic health
                interventions through service platforms ranging from the community to the
                primary health center and the hospital. This volume presents the levels and
                trends of RMNCH indicators, proven interventions for prevention of mortality,
                costs of these interventions and potential health service delivery platforms,
                and system innovations. Other volumes in the third edition of Disease Control
                Priorities also cover topics of importance to women and children that are
                related to the RMNCH health services packages (box 1.1). These topics include
                the following: Trauma care; obstetric surgery; obstetric fistula; surgery for
                family planning, abortion, and postabortion care; and surgery for congenital
                anomalies (Volume 1, Essential Surgery). Breast cancer, cervical cancer and
                precancer, childhood cancer, and cancer pain relief (Volume 3, Cancer).
                Childhood mental and developmental disorders (Volume 4, Mental, Neurological,
                and Substance Use Disorders). Cardiovascular and respiratory disorders (Volume
                5, Cardiovascular, Respiratory, and Related Disorders). HIV/AIDS and other
                sexually transmitted infections, tuberculosis, and malaria (Volume 6, HIV/AIDS,
                STIs, tuberculosis, and Malaria). Road traffic injury and interpersonal violence
                (Volume 7, Injury Prevention and Environmental Health). Child (older than five
                years) and adolescent development (the subject of the entire Volume 8, Child and
                Adolescent Development).
            </abstract>
            <work-type>
                Book
            </work-type>
            <urls></urls>
            <electronic-resource-num>
                10.1596/978-1-4648-0348-2_ch1
            </electronic-resource-num>
            <remote-database-provider>
                NLM
            </remote-database-provider>
            <language>
                English
            </language>
        </record>
        <record>
            <contributors>
                <authors>
                    <author>
                        Story, A.
                    </author>
                    <author>
                        Garber, E.
                    </author>
                    <author>
                        Aldridge, R. W.
                    </author>
                    <author>
                        Smith, C. M.
                    </author>
                    <author>
                        Hall, J.
                    </author>
                    <author>
                        Ferenando, G.
                    </author>
                    <author>
                        Possas, L.
                    </author>
                    <author>
                        Hemming, S.
                    </author>
                    <author>
                        Wurie, F.
                    </author>
                    <author>
                        Luchenski, S.
                    </author>
                    <author>
                        Abubakar, I.
                    </author>
                    <author>
                        McHugh, T. D.
                    </author>
                    <author>
                        White, P. J.
                    </author>
                    <author>
                        Watson, J. M.
                    </author>
                    <author>
                        Lipman, M.
                    </author>
                    <author>
                        Garfein, R.
                    </author>
                    <author>
                        Hayward, A. C.
                    </author>
                </authors>
            </contributors>
            <auth-address>
                Institute of Health Informatics,
                University College London, London, UK&#xD;Find&amp;Treat, University College
                Hospitals NHS Foundation Trust, London, UK&#xD;Royal Free London NHS Foundation
                Trust, London, UK&#xD;Institute for Global Health, University College London,
                London, UK&#xD;Centre for Clinical Microbiology, University College London,
                London, UK&#xD;Medical Research Council Centre for Global Infectious Disease
                Analysis, Department of Infectious Disease Epidemiology, School of Public
                Health, Imperial College London, London, UK&#xD;National Institute for Health
                Research Health Protection Research Unit in Modelling Methodology, Department of
                Infectious Disease Epidemiology, School of Public Health, Imperial College
                London, London, UK&#xD;Modelling and Economics Unit, National Infection Service,
                Public Health England, London, UK&#xD;Research Department of Infection and
                Population Health, University College London, London, UK&#xD;Respiratory
                Medicine, Division of Medicine, University College London, London,
                UK&#xD;Division of Global Public Health, School of Medicine, University of
                California, San Diego, CA, USA&#xD;Institute of Epidemiology and Health Care,
                University College London, London, UK
            </auth-address>
            <titles>
                <title>
                    Management and control of
                    tuberculosis control in socially complex groups: a research programme
                    including three RCTs
                </title>
            </titles>
            <keywords>
                <keyword>
                    disease control
                </keyword>
            </keywords>
            <year>
                2020
            </year>
            <pub-location>
                Southampton (UK)
            </pub-location>
            <publisher>
                NIHR Journals Library
            </publisher>
            <abstract>
                BACKGROUND: Socially complex groups,
                including people experiencing homelessness, prisoners and drug users, have very
                high levels of tuberculosis, often complicated by late diagnosis and difficulty
                in adhering to treatment. OBJECTIVE: To assess a series of interventions to
                improve tuberculosis control in socially complex groups. DESIGN: A series of
                observational surveys, evaluations and trials of interventions. SETTING: The
                pan-London Find&amp;Treat service, which supports tuberculosis screening and
                case management in socially complex groups across London. PARTICIPANTS: Socially
                complex groups with tuberculosis or at risk of tuberculosis, including people
                experiencing homelessness, prisoners, drug users and those at high risk of poor
                adherence to tuberculosis treatment. INTERVENTIONS AND MAIN OUTCOME MEASURES: We
                screened 491 people in homeless hostels and 511 people in prison for latent
                tuberculosis infection, human immunodeficiency virus, hepatitis B and hepatitis
                C. We evaluated an NHS-led prison radiographic screening programme. We conducted
                a cluster randomised controlled trial (2348 eligible people experiencing
                homelessness in 46 hostels) of the effectiveness of peer educators (22 hostels)
                compared with NHS staff (24 hostels) at encouraging the uptake of mobile
                radiographic screening. We initiated a trial of the use of point-of-care
                polymerase chain reaction diagnostics to rapidly confirm tuberculosis alongside
                mobile radiographic screening. We undertook a randomised controlled trial to
                improve treatment adherence, comparing face-to-face, directly observed treatment
                with video-observed treatment using a smartphone application. The primary
                outcome was completion of ≥ 80% of scheduled treatment observations over the
                first 2 months following enrolment. We assessed the cost-effectiveness of latent
                tuberculosis screening alongside radiographic screening of people experiencing
                homelessness. The costs of video-observed treatment and directly observed
                treatment were compared. RESULTS: In the homeless hostels, 16.5% of people
                experiencing homelessness had latent tuberculosis infection, 1.4% had current
                hepatitis B infection, 10.4% had hepatitis C infection and 1.0% had human
                immunodeficiency virus infection. When a quality-adjusted life-year is valued at
                £30,000, the latent tuberculosis screening of people experiencing homelessness
                was cost-effective provided treatment uptake was ≥ 25% (for a £20,000
                quality-adjusted life-year threshold, treatment uptake would need to be &gt;
                50%). In prison, 12.6% of prisoners had latent tuberculosis infection, 1.9% had
                current hepatitis B infection, 4.2% had hepatitis C infection and 0.0% had human
                immunodeficiency virus infection. In both settings, levels of latent
                tuberculosis infection and blood-borne viruses were higher among injecting drug
                users. A total of 1484 prisoners were screened using chest radiography over a
                total of 112 screening days (new prisoner screening coverage was 43%).
                Twenty-nine radiographs were reported as potentially indicating tuberculosis.
                One prisoner began, and completed, antituberculosis treatment in prison. In the
                cluster randomised controlled trial of peer educators to increase screening
                uptake, the median uptake was 45% in the control arm and 40% in the intervention
                arm (adjusted risk ratio 0.98, 95% confidence interval 0.80 to 1.20). A rapid
                diagnostic service was established on the mobile radiographic unit but the trial
                of rapid diagnostics was abandoned because of recruitment and follow-up
                difficulties. We randomly assigned 112 patients to video-observed treatment and
                114 patients to directly observed treatment. Fifty-eight per cent of those
                recruited had a history of homelessness, addiction, imprisonment or severe
                mental health problems. Seventy-eight (70%) of 112 patients on video-observed
                treatment achieved the primary outcome, compared with 35 (31%) of 114 patients
                on directly observed treatment (adjusted odds ratio 5.48, 95% confidence
                interval 3.10 to 9.68; p &lt; 0.0001). Video-observed treatment was superior to
                directly observed treatment in all demographic and social risk factor subgroups.
                The cost for 6 months of treatment observation was £1645 for daily
                video-observed treatment, £3420 for directly observed treatment three times per
                week and £5700 for directly observed treatment five times per week. LIMITATIONS:
                Recruitment was lower than anticipated for most of the studies. The peer
                advocate study may have been contaminated by the fact that the service was
                already using peer educators to support its work. CONCLUSIONS: There are very
                high levels of latent tuberculosis infection among prisoners, people
                experiencing homelessness and drug users. Screening for latent infection in
                people experiencing homelessness alongside mobile radiographic screening would
                be cost-effective, providing the uptake of treatment was 25–50%. Despite
                ring-fenced funding, the NHS was unable to establish static radiographic
                screening programmes. Although we found no evidence that peer educators were
                more effective than health-care workers in encouraging the uptake of mobile
                radiographic screening, there may be wider benefits of including peer educators
                as part of the Find&amp;Treat team. Utilising polymerase chain reaction-based
                rapid diagnostic testing on a mobile radiographic unit is feasible.
                Smartphone-enabled video-observed treatment is more effective and cheaper than
                directly observed treatment for ensuring that treatment is observed. FUTURE
                WORK: Trials of video-observed treatment in high-incidence settings are needed.
                TRIAL REGISTRATION: Current Controlled Trials ISRCTN17270334 and ISRCTN26184967.
                FUNDING: This project was funded by the National Institute for Health Research
                (NIHR) Programme Grants for Applied Research programme and will be published in
                full in Programme Grants for Applied Research; Vol. 8, No. 9. See the NIHR
                Journals Library website for further project information.&#xD;This research
                programme found that homeless people and prisoners have high levels of
                undiagnosed latent TB and hepatitis C, and smartphone-enabled video was more
                effective and cheaper than direct observation of TB.&#xD;eng
            </abstract>
            <work-type>
                Book
            </work-type>
            <urls>
                <related-urls>
                    <url>
                        https://njl-admin.nihr.ac.uk/document/download/2034457
                    </url>
                </related-urls>
                <pdf-urls>
                    <url>internal-pdf://2165627069/Story-2020-Programme Grants for Applied
                        Resear.pdf</url>
                </pdf-urls>
            </urls>
            <electronic-resource-num>
                10.3310/pgfar08090
            </electronic-resource-num>
            <remote-database-provider>
                NLM
            </remote-database-provider>
            <language>
                English
            </language>
        </record>
        <record>
            <contributors>
                <authors>
                    <author>
                        Bennett, K. P.
                    </author>
                    <author>
                        Ozcaglar, C.
                    </author>
                    <author>
                        Ranganathan, J.
                    </author>
                    <author>
                        Raghavan, S.
                    </author>
                    <author>
                        Katz, J.
                    </author>
                    <author>
                        Croft, D.
                    </author>
                    <author>
                        Yener, B.
                    </author>
                    <author>
                        Shabbeer, A.
                    </author>
                </authors>
            </contributors>
            <titles>
                <title>
                    Visualization of tuberculosis
                    patient and mycobacterium tuberculosis complex genotype data via
                    host-pathogen maps
                </title>
                <secondary-title>
                    2011 IEEE International
                    Conference on Bioinformatics and Biomedicine Workshops, BIBMW 2011
                </secondary-title>
            </titles>
            <pages>
                124-129
            </pages>
            <volume>
                null
            </volume>
            <number>
                null
            </number>
            <keywords>
                <keyword>
                    tuberculosis
                </keyword>
                <keyword>
                    host-pathogen maps
                </keyword>
                <keyword>
                    spoligotypes
                </keyword>
                <keyword>
                    tree-maps
                </keyword>
                <keyword>
                    tuberculosis
                </keyword>
                <keyword>
                    visualization
                </keyword>
                <keyword>
                    forestry
                </keyword>
                <keyword>
                    maps
                </keyword>
                <keyword>
                    pathogens
                </keyword>
                <keyword>
                    trees
                </keyword>
                <keyword>
                    data visualization
                </keyword>
                <keyword>
                    disease control
                </keyword>
                <keyword>
                    flow visualization
                </keyword>
                <keyword>
                    hospital data processing
                </keyword>
                <keyword>
                    control effort
                </keyword>
                <keyword>
                    dna fingerprinting
                </keyword>
                <keyword>
                    dna fingerprints
                </keyword>
                <keyword>
                    genotyping
                </keyword>
                <keyword>
                    mycobacterium tuberculosis
                </keyword>
                <keyword>
                    new york city
                </keyword>
                <keyword>
                    new york state
                </keyword>
                <keyword>
                    patient data
                </keyword>
                <keyword>
                    phylogenetic trees
                </keyword>
                <keyword>
                    restriction fragment length
                    polymorphisms
                </keyword>
                <keyword>
                    surveillance data
                </keyword>
                <keyword>
                    patients
                </keyword>
            </keywords>
            <year>
                2011
            </year>
            <abstract>
                DNA fingerprints of mycobacterium
                tuberculosis complex bacteria (MTBC) are routinely gathered from tuberculosis
                (TB) patient isolates for all TB patients in the United States to support TB
                tracking and control efforts, but few tools are available for visualizing and
                discovering host-pathogen relationships. We present a new visualization
                approach, host-pathogen maps, for simultaneously examining MTBC strains
                genotyped by multiple DNA fingerprinting methods such as spoligotyping and
                restriction fragment length polymorphisms (RFLP) typing along with associated
                patient surveillance data. The host-pathogen maps are dynamically coupled with
                spoligoforests or other phylogenetic tree approaches to allow easy navigation
                within the pathogen genotyping space. Visualization of New York State and New
                York City (NYC) TB patient data from 2001-2007 is used to illustrate how
                host-pathogen maps can be used to rapidly identify potential instances of
                uncontrolled spread of tuberculosis versus disease resulting from latent
                reactivation of prior infection, a critical distinction in tuberculosis control.
                Host-pathogen maps also reveal trends and anomalies in the relationships between
                patient groups and MTBC genetic lineages which can provide critical clues in
                epidemiology and contact investigations of TB. © 2011 IEEE.
            </abstract>
            <work-type>
                Conference paper
            </work-type>
            <urls></urls>
            <electronic-resource-num>
                10.1109/BIBMW.2011.6112364
            </electronic-resource-num>
            <remote-database-provider>
                Scopus
            </remote-database-provider>
            <language>
                English
            </language>
        </record>
        <record>
            <contributors>
                <authors>
                    <author>
                        Kumar, R.
                    </author>
                    <author>
                        Gandham, S.
                    </author>
                    <author>
                        Rana, A.
                    </author>
                    <author>
                        Maity, H. K.
                    </author>
                    <author>
                        Sarkar, U.
                    </author>
                    <author>
                        Dey, B.
                    </author>
                </authors>
            </contributors>
            <auth-address>
                B. Dey, National Institute of Animal
                Biotechnology, Telangana, Hyderabad, India
            </auth-address>
            <titles>
                <title>
                    Divergent proinflammatory immune
                    responses associated with the differential susceptibility of cattle breeds
                    to tuberculosis
                </title>
                <secondary-title>
                    bioRxiv
                </secondary-title>
            </titles>
            <keywords>
                <keyword>
                    mycobacterium bovis
                </keyword>
                <keyword>
                    animal cell
                </keyword>
                <keyword>
                    animal experiment
                </keyword>
                <keyword>
                    animal tissue
                </keyword>
                <keyword>
                    bacterial growth
                </keyword>
                <keyword>
                    bovine tuberculosis
                </keyword>
                <keyword>
                    cattle breed
                </keyword>
                <keyword>
                    controlled study
                </keyword>
                <keyword>
                    ex vivo study
                </keyword>
                <keyword>
                    gene expression
                </keyword>
                <keyword>
                    genetic transcription
                </keyword>
                <keyword>
                    immune response
                </keyword>
                <keyword>
                    incidence
                </keyword>
                <keyword>
                    india
                </keyword>
                <keyword>
                    innate immunity
                </keyword>
                <keyword>
                    multiplex polymerase chain
                    reaction
                </keyword>
                <keyword>
                    mycobacteriosis
                </keyword>
                <keyword>
                    mycobacterium bovis bcg
                </keyword>
                <keyword>
                    mycobacterium tuberculosis
                </keyword>
                <keyword>
                    mycobacterium tuberculosis
                    complex
                </keyword>
                <keyword>
                    nonhuman
                </keyword>
                <keyword>
                    peripheral blood mononuclear
                    cell
                </keyword>
                <keyword>
                    prevalence
                </keyword>
                <keyword>
                    protein expression
                </keyword>
                <keyword>
                    reactor
                </keyword>
                <keyword>
                    signal transduction
                </keyword>
                <keyword>
                    tuberculin test
                </keyword>
                <keyword>
                    tuberculosis
                </keyword>
                <keyword>
                    cytokine
                </keyword>
                <keyword>
                    endogenous compound
                </keyword>
                <keyword>
                    gamma interferon
                </keyword>
                <keyword>
                    interleukin 17
                </keyword>
                <keyword>
                    interleukin 1beta
                </keyword>
                <keyword>
                    phosphotransferase
                </keyword>
                <keyword>
                    tuberculin